### PR TITLE
Fix timeUntilLeaseEntersDangerZone calculation

### PR DESCRIPTION
**Pull request by dougdonohoe**
I noticed that `dynamolock.WithSessionMonitor` wasn't behaving as I was expecting.  I was setting a lease to 10 seconds and a monitor to 1 second and I was getting the callback after one second expired, not after 9 seconds (with 1 second left to go).  Based on my reading of the docs, I think the intended behavior is that you get the callback when `safeTime` remains before timeout.

The actual fix is in the `timeUntilLeaseEntersDangerZone` calculation.

I also modified tests so one can use `DYNAMODB_LOCAL_HOST` to specify alternate local dynamo host for tests (useful in my environment where I've already got Dynamo running).  I used this to test the V1 code (which we may be using):

```
make test DYNAMODB_LOCAL_HOST="http://localhost:52088"
```

### CODE REVIEW

**Comment by ucirello** [comment]
Could you please point me in the original Java implementation the behavior you're describing? 

I try to keep both Java and Go version using the same semantics.

**Comment by dougdonohoe** [comment]
I'm not familiar with the Java implementation.  I'm just basing it off of common sense and the comments in the code.

**Comment by ucirello** [comment]
For reference: https://github.com/awslabs/amazon-dynamodb-lock-client/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/SessionMonitor.java#L47-L74

**Comment by ucirello** [comment]
@dougdonohoe - I think you may have found a documentation bug rather than an implementation bug. If I am reading the Java code correctly, it seems this dynamolock is doing the same thing as the original in Java. 

What problems the current API caused you?

**Comment by dougdonohoe** [comment]
I think I understand my misunderstanding.  If the lease is 10 seconds and I want to be warned when a second is left, the safe time needs to be 9 seconds.

**Comment by ucirello** [comment]
@dougdonohoe - I will try to improve the docs. Thanks for the report.

**Pull request closed without merging**
