### PR TITLE
WIP: Fix data race in is expired

### PR DESCRIPTION
**Pull request by hikhvar**

### CODE REVIEW

**Comment by ucirello** [comment]
Thanks for the PR @hikhvar -- looking forward to review it when you are done.

**Comment by hikhvar** [comment]
After activating the race detector in the tests, a lot of  tests fail. It may take some time to fix them.

**Comment by ucirello** [comment]
@hikhvar - focus on the one you found. I am taking care of the rest here now.

**Comment by ucirello** [comment]
@hikhvar in order to be able to apply my fixes, I am going to need to merge this one first. I am merging this PR now, even if Travis is not happy about it because I need this fix to make progress here. 

Merging this PR now, please keep an eye in the upcoming release.

**Pull request merged**
