### PR TITLE
Adds context to logger interface.

### PR DESCRIPTION
**Pull request by mavenraven**
Hi @ucirello ! Thanks so much for making this library! 

This PR adds context to the logging interface. The use case that we're running into is that with the current interface, there's no way to add a correlation id to the log line. This makes it almost impossible for us to consume dynamolock's log output in any meaningful way.

I saw that you don't promise backwards compatibility, but I'm happy to re-do this in a backwards compatible way if desired. Thank you!

### CODE REVIEW

**Comment by ucirello** [comment]
hi @mavenraven -- thanks for opening this PR. I wished you had opened an issue first to discuss this use case before proposing a change. As it is, I am afraid I am going to have to reject it. You added the extra parameter in the interface, but it is used nowhere. Moreover, it makes the extension of the logging facilities harder for every other extension case. 

From what I could understand, all you need is to supply the client with a custom logger that has the context you want in it. Something along the lines

```

const requestID = ...

type ContextLogger struct {
        ctx context.Context
}

func (cl *ContextLogger) Println(v ...interface{}) { 
        log.Println(append([]interface{}{ctx.Value(requestID),":"}, v...)...)
}

func NewContextLogger(ctx context.Context) *ContextLogger {
        return &ContextLogger{ctx: ctx}
}

//---

c := dynamolock.New(svc, "locks", dynamolock.WithLogger(NewContextLogger(ctx)))
```

Thanks and good luck.

**Comment by mavenraven** [comment]
Hey @ucirello, that doesn't actually work. We need to use the context that's passed into `AcquireLockWithContext`. The context that you suggested is at instantiation time. As we only instantiate the client on startup, there's no way to get a request correlation ID at that point.

As far as the context not being used: that's true, but only for the default implementation. In our codebase, we need an adapter that pulls the correlation ID out of context and uses it as a field for (zap)[https://pkg.go.dev/go.uber.org/zap#String]. It's currently impossible to do this.

I hope you will reconsider!

**Comment by mavenraven** [comment]
Here's an example line of what the output looks like in our logs using our adapter:
```
2021-05-13T11:33:05.156-0400    INFO    dynlock/zap_log_adapter.go:24   log line for dynamolock :[Acquiring a new lock or an existing yet released lock on  key = singularity_lock_0:i50ugt5m5b39]      {"app": "singularity", "correlation_id": "fb811a31-7bd4-420e-9de9-72f200345fc5", "method_name": "PutDatabaseBranch"}
```

**Comment by ucirello** [comment]
@mavenraven -- thanks for sharing the context. I am going to reopen this and analyze it further, OK?

**Comment by mavenraven** [comment]
awesome, thank you @ucirello!

**Comment by ucirello** [comment]
@mavenraven - if you made this backward compatible, how would it look like?

**Comment by mavenraven** [comment]
@ucirello I was thinking something like [this](https://github.com/mavenraven/dynamolock/compare/master...mavenraven:example).

**Comment by ucirello** [comment]
Thanks @mavenraven - could you please update the PR with https://github.com/mavenraven/dynamolock/compare/master...mavenraven:example ?

**Comment by ucirello** [comment]
ping?

**Comment by mavenraven** [comment]
Hey @ucirello ! Sorry, I've been super busy. I might be able to to do it today.

**Comment by mavenraven** [comment]
@ucirello Ok, I just added it.

**Pull request merged**
