### PR TITLE
Make Lock expose record revision number

### PR DESCRIPTION
**Pull request by milton0825**
Add a method to expose lock record revision number.

### Some context
We are planning to add some monitoring to ensure that there is an active leader by checking if the record revision number is constantly changing.

### CODE REVIEW

**Comment by milton0825** [comment]
@ucirello @sw-square

**Comment by ucirello** [comment]
hi @milton0825 -- thanks for this PR.

I wished that you had opened an issue first to discuss before making this change.

In any case, as it is, it is broken and I cannot merge.

The purpose of the `Get` calls is to give you access to the content of the Lock, but without giving away the artifacts to change its lifecycle. In this case, the `recordVersionNumber` could be misused and create confusion about lock ownership.

**Review by ucirello — CHANGES_REQUESTED** [review]
Get is meant to return a read-only view of the Lock, returning the RVN may encourage misuse.

**Comment by milton0825** [comment]
Just opened https://github.com/cirello-io/dynamolock/issues/179 let's move the discussion over there.

**Pull request closed without merging**
