### PR TITLE
Adding the tags in the creation of the dynamo db tables

### PR DESCRIPTION
**Pull request by piclemx**
First, really like the project you have made.

I think it will be a great feature to this projet to be able to create the tables in AWS with tags.

Because tags in big companies are used for governances, billings and other things.

It will make it compatible with project like cloudcustodian that can delete AWS ressources if they aren't tagged.

This is just a WIP for the moment. I will add the test and missing parts soon.

### CODE REVIEW

**Comment by ucirello** [comment]
Thanks for the PR. Go for it.

Meanwhile, please, restore .gitignore and go.sum.

**Comment by ucirello** [comment]
Ping @piclemx

**Comment by ucirello** [comment]
Any progress @piclemx ?

**Comment by piclemx** [comment]
Sorry I wasn’t able to do anything during the holidays. I will try to complete this beginning next week

**Comment by piclemx** [comment]
@ucirello I have made the changes you ask.

**Comment by ucirello** [comment]
Thanks @piclemx

**Comment by piclemx** [comment]
You're welcome 😄

**Pull request merged**
